### ISSUE TITLE
Feature Request: Show colors of LEDs for DS4

### ISSUE THREAD

**Issue by DamianS-eng** [Nielk1/VSCView#35]
I know that DS4Windows can already output the intended lightbar color, it'd be nice to see this shown on the default theme for the Playstation controllers in VSCView. There are some ways to change the LEDs in Steam and ReWASD, and it'd be consistent to show the changes on the view when making tutorials for LEDs or mode shifts.
![lightbar](https://user-images.githubusercontent.com/12158234/114914695-9f953600-9df0-11eb-8708-d73b89f7763c.png)
Above is a poor artist's interpretation.

**Comment by Nielk1** [comment]
Can't do it.  You can't read the state of the LED.  If VSCView was setting the LED color, it would know what it set it to, but it isn't setting it.  Only way to do it otherwise would be a filter driver (yes, an actual driver) eavesdropping on all writes going out to the controller or somehow memory watching Steam (which is risky and would break every Steam update).

With a variable system added to the existing formula system it could probably be faked with large complex formulas in the theme that change the color with specific button combos, but that would be extremely complex and only fit a single specific case after hours of work.

If SteamInput or ReWASD have some sort of event I can hook to, detect the color set event with the color and enough information to confirm it's form the DS4 in question, I could do it that way, but that is a lot of big IFs and all experience says the answer to all of them is no.

**Comment by DamianS-eng** [comment]
Gotcha, thanks for humoring the thought.

**Comment by AL2009man** [comment]
As I was in a middle of updating the DS4 Theme (and making a DualSense theme), I thought about it. 

While I knew about the potential technical limitations with said feature, I already have a separate Base Controller Template where I took out the Lightbar functionality and make it as its own .png image. For the time being, the current DS4/DualSense Theme is bake-in.

When Nielk figured out how to show the LED Functionality within VSCView, he can happily swap the Base Image and implement the Lightbar .png files and go nuts with it.
