### ISSUE TITLE
Support for the DualSense Controller

### ISSUE THREAD

**Issue by andreycout** [Nielk1/VSCView#37]
Currently VSCView doesn't pickup the Dualsense inputs (PlayStation 5 Controller), even though Steam supports it. Any easy way to add it?

**Comment by AL2009man** [comment]
the release build of VSCView doesn't support the DualSense Controller right now, but if you know how to compile from source; [DualSense support has been added to VSCView since February 1st, 2021](https://github.com/Nielk1/VSCView/commit/5fbe91118fc78f58386980299045ef3a44a20c03) and you can check it out. But, it's currently buggy...more so on Wireless mode.

it doesn't help that Nielk1 is in a middle of refactoring VSCView + ExtendInput, it may take longer.

As for DualSense theme, I already completed the theme a few months ago, but I recently came back and finalized all the necessary .json files to bring it over to VSCView (master build).

**Comment by andreycout** [comment]
@AL2009man I have no idea how to compile this and I haven't found instructions... but I'd appreciate it immensely if you could send me a compiled build with this DualSense fix while a new release is pending. Just switched to the DualSense and I really miss having a gamepad osd that I can use with Steam Input like I did with the DualShock 4.

**Comment by lucas-oliveira-gomes** [comment]
Thank you @AL2009man .
I tasted it and worked like a charm.
Many Thanks
![VSCView_DualSense_Theme](https://user-images.githubusercontent.com/1829329/125482878-6b05aa22-d4f0-4168-8e5a-e33387ed5901.gif)

@andreycout I just used Microsoft Visual Studio Community 2019, it is free, I guess you can use it too if you want a preview.
Looking forward for the official release.

**Comment by andreycout** [comment]
I was missing some dependencies, just got it to work on my end as well. Very nice! It doesn't auto-select the DualSense when I open VSCView though, even though I changed my cfg to do so. I'm not sure if it has anything to do with the DualSense implementation or just the program itself because I don't have anything else to test it with right now.

**Comment by Nielk1** [comment]
I'm going to close this because the DualSense is implemented but just not yet in a pre-built release.  The main issue right now is trying to stomp any bugs and pick the best place to stop and release a stop-gap version with the DS(5) support.

**Comment by AL2009man** [comment]
> Thank you @AL2009man .
> I tasted it and worked like a charm.
> Many Thanks
> ![VSCView_DualSense_Theme](https://user-images.githubusercontent.com/1829329/125482878-6b05aa22-d4f0-4168-8e5a-e33387ed5901.gif)
> 
> @andreycout I just used Microsoft Visual Studio Community 2019, it is free, I guess you can use it too if you want a preview.
> Looking forward for the official release.

nice. That's how I learned how to compile stuffs. :) 

Anyway, I still got theme stuffs I wanna get it done before the stop-gap release. I may get all of them done by the time Nielk finished clean up the bugs.
